import { RollingBannerWrapper, RowLeft, RowRight } from './style';

const RollingBanner = () => {
    const { movies, tvShows } = useSelector((state) => state.contentR);

    return (
        <RollingBannerWrapper>
            <RowRight>
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/membership/pc-logo.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
            </RowRight>

            <RowLeft>
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/membership/pc-logo.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
            </RowLeft>

            <RowRight>
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/membership/pc-logo.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
                <img
                    src='https://github.com/lse-7660/bokjak-image/blob/main/images/main/intro/introSlide1.png?raw=true'
                    alt=''
                />
            </RowRight>
        </RollingBannerWrapper>
    );
};

export default RollingBanner;
